set(LOCAL_WIFI_SSID "your-wifi-name")
set(LOCAL_WIFI_PASSWORD "your-wifi-password")

set(LOCAL_MQTT_BROKER_IP_0 192)
set(LOCAL_MQTT_BROKER_IP_1 168)
set(LOCAL_MQTT_BROKER_IP_2 1)
set(LOCAL_MQTT_BROKER_IP_3 10)
set(LOCAL_MQTT_BROKER_PORT 1883)